#
# Makefile for the kernel Sensor device drivers.
#

# Object files in subdirectories

obj-$(CONFIG_PROXLIGHT)			+= proxlight/
obj-$(CONFIG_COMPASS)			+= compass/
obj-$(CONFIG_MPU_SENSORS_MPU3050_V333)	+= mpu3050_v333/
